//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBFirstStudentDataBase_School_.Utils
{
    using System;
    using System.Collections.Generic;
    
    public partial class loggerTable
    {
        public int logID { get; set; }
        public string logData { get; set; }
        public string createdDate { get; set; }
    }
}
